import { Pool } from "pg";
import { assertTransition, hashDeletionSecret, generateDeletionSecret, signDraftCapability, verifyDraftCapability } from "@chibbo/domain";
import { databaseConnectionOptions, loadConfig } from "@chibbo/config";
import { createProductionUploadPost, localOnlyUploadPolicy, verifyAndPromoteVersion, compensatePromotion, getAcceptedResume } from "@chibbo/storage";
import { randomUUID } from "node:crypto";
import { S3Client } from "@aws-sdk/client-s3";
import { validateAuditEvent } from "@chibbo/audit";
import { withActorTransaction, withTenantTransaction } from "@chibbo/db";
import { createOpaqueSessionToken, hashSessionToken, principalFromMembership, type StaffPrincipal } from "@chibbo/auth";
import { anonymousKey, consumePostgresWindow } from "@chibbo/rate-limit";

let pool: Pool | undefined;
function database(): Pool { return (pool ??= new Pool({ ...databaseConnectionOptions(loadConfig()), max: 5 })); }
function productionStorage() { const config = loadConfig(); if (config.CHIBBO_STORAGE_MODE !== "s3" || !config.CHIBBO_RESUME_BUCKET || !config.CHIBBO_RESUME_KMS_KEY_ID) throw new Error("S3 resume storage is not configured"); return { bucket: config.CHIBBO_RESUME_BUCKET, kmsKeyId: config.CHIBBO_RESUME_KMS_KEY_ID, client: new S3Client({}) }; }
export type DraftInput = { companySlug: string; jobSlug: string; applicantName: string; applicantEmail: string; applicantPhone?: string; privacyNoticeVersion: string; mediaType: string };
export async function createDraft(input: DraftInput) {
  const config = loadConfig(); const intentId = randomUUID(); const receipt = `CH-${Date.now().toString(36).toUpperCase()}-${randomUUID().slice(0, 6).toUpperCase()}`; const deletionSecret = generateDeletionSecret();
  const result = await database().query("SELECT * FROM chibbo.create_public_draft($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,now() + interval '10 minutes',$11)", [input.companySlug, input.jobSlug, input.applicantName, input.applicantEmail.toLowerCase(), input.privacyNoticeVersion, hashDeletionSecret(deletionSecret, config.CHIBBO_DELETION_PEPPER), "current", intentId, receipt, input.mediaType, input.applicantPhone ?? null]);
  if (result.rowCount !== 1) throw new Error("draft creation failed");
  const companyId = result.rows[0].company_id as string;
  const upload = config.CHIBBO_STORAGE_MODE === "s3" ? { adapter: "s3-presigned-post", ...(await createProductionUploadPost(productionStorage(), intentId, input.mediaType)) } : process.env.NODE_ENV === "test" ? { adapter: "local-only-test-adapter", ...localOnlyUploadPolicy(intentId, input.mediaType, "alias/chibbo-resumes") } : (() => { throw new Error("S3 storage is required outside tests"); })();
  return { intentId, receipt, deletionSecret, companyId, draftCapability: signDraftCapability({ intentId, companyId, expiresAt: Date.now() + 10 * 60_000 }, config.CHIBBO_DELETION_PEPPER), upload };
}
export async function finalizeIntent(intentId: string, versionId: string, sha256: string, draftCapability: string) {
  const config = loadConfig(); const capability = verifyDraftCapability(draftCapability, config.CHIBBO_DELETION_PEPPER); if (capability.intentId !== intentId) throw new Error("draft capability does not match intent");
  return withTenantTransaction(database(), { companyId: capability.companyId, tenantId: "00000000-0000-4000-8000-000000000000", objectId: "00000000-0000-4000-8000-000000000000", role: "company-manager" }, async (client) => {
  let promotedKey: string | undefined;
  try { const intent = await client.query("SELECT * FROM chibbo.upload_intents WHERE id=$1 FOR UPDATE", [intentId]); if (intent.rowCount !== 1) throw new Error("not found"); const row = intent.rows[0]; if (row.company_id !== capability.companyId || row.state !== "issued" || new Date(row.expires_at) < new Date()) throw new Error("upload intent is unavailable"); await client.query("UPDATE chibbo.upload_intents SET state='verifying', updated_at=now() WHERE id=$1 AND state='issued'", [intentId]); const result = config.CHIBBO_STORAGE_MODE === "s3" ? await verifyAndPromoteVersion(productionStorage(), { intentId, key: row.object_key, versionId, mediaType: row.expected_media_type, sha256 }) : { acceptedKey: `accepted/${intentId}`, sizeBytes: 1, versionId }; promotedKey = result.acceptedKey; await client.query("UPDATE chibbo.upload_intents SET state='finalized', object_version_id=$2, updated_at=now() WHERE id=$1", [intentId, versionId]); await client.query("INSERT INTO chibbo.resumes(company_id,application_id,upload_intent_id,bucket,object_key,object_version_id,sha256,media_type,size_bytes,verification_status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'accepted')", [row.company_id, row.application_id, intentId, config.CHIBBO_RESUME_BUCKET ?? "local-test-only", result.acceptedKey, result.versionId, sha256.toLowerCase(), row.expected_media_type, result.sizeBytes]); await client.query("UPDATE chibbo.applications SET status='submitted', row_version=row_version+1 WHERE id=$1 AND status='draft_upload'", [row.application_id]); validateAuditEvent({ correlationId: intentId, eventScope: "recruitment-service", eventSource: "application-audit", companyId: row.company_id, action: "application.submitted", targetType: "application", targetId: row.application_id }); await client.query("INSERT INTO chibbo.audit_events(company_id,correlation_id,event_scope,event_source,action,target_type,target_id) VALUES($1,$2,$3,$4,$5,$6,$7)", [row.company_id, intentId, "recruitment-service", "application-audit", "application.submitted", "application", row.application_id]); return { applicationId: row.application_id }; } catch (error) { if (promotedKey && config.CHIBBO_STORAGE_MODE === "s3") await compensatePromotion(productionStorage(), promotedKey); throw error; } }); }

export async function resolveStaffSession(token: string | undefined): Promise<StaffPrincipal> { if (!token) throw Object.assign(new Error("not found"), { status: 404 }); const result = await database().query("SELECT * FROM chibbo.resolve_active_session($1)", [hashSessionToken(token)]); const row = result.rows[0]; return principalFromMembership(row && { tenantId: row.entra_tenant_id, objectId: row.entra_object_id, companyId: row.company_id ?? undefined, role: row.role, active: true, membershipVersion: row.membership_version }); }
export async function createStaffSession(identity: { tid: string; oid: string }) { const token = createOpaqueSessionToken(); const result = await database().query("SELECT * FROM chibbo.create_staff_session($1,$2,$3)", [hashSessionToken(token), identity.tid, identity.oid]); if (result.rowCount !== 1) throw Object.assign(new Error("not found"), { status: 404 }); return { token, principal: principalFromMembership({ tenantId: identity.tid, objectId: identity.oid, companyId: result.rows[0].company_id ?? undefined, role: result.rows[0].role, membershipVersion: result.rows[0].membership_version, active: true }) }; }
export async function consumeAnonymousRateLimit(request: Request, scope: "upload-init" | "upload-finalize" | "deletion") {
  const config = loadConfig(); const forwarded = request.headers.get("x-forwarded-for"); const ip = (forwarded?.split(",")[0]?.trim() || request.headers.get("x-real-ip") || "unknown").slice(0, 128);
  const limits = { "upload-init": [600, 10], "upload-finalize": [600, 10], deletion: [3600, 5] } as const;
  const [seconds, maximum] = limits[scope]; const result = await consumePostgresWindow(database(), scope, anonymousKey(ip, config.CHIBBO_DELETION_PEPPER), seconds, maximum);
  if (!result.allowed) throw Object.assign(new Error("rate limited"), { status: 429, retryAfterSeconds: result.retryAfterSeconds });
}
export async function listStaffApplications(principal: StaffPrincipal) { if (principal.role !== "company-manager" || !principal.companyId) throw Object.assign(new Error("not found"), { status: 404 }); return withTenantTransaction(database(), { ...principal, companyId: principal.companyId }, (client) => client.query("SELECT * FROM chibbo.list_staff_applications()")); }
export async function getStaffApplication(principal: StaffPrincipal, applicationId: string) { if (principal.role !== "company-manager" || !principal.companyId) throw Object.assign(new Error("not found"), { status: 404 }); return withTenantTransaction(database(), { ...principal, companyId: principal.companyId }, async (client) => { const result = await client.query("SELECT * FROM chibbo.get_staff_application($1)", [applicationId]); if (result.rowCount !== 1) throw Object.assign(new Error("not found"), { status: 404 }); const resume = await client.query("SELECT bucket,object_key,object_version_id,media_type FROM chibbo.resumes WHERE application_id=$1", [applicationId]); return { ...result.rows[0], resume: resume.rows[0] ?? null }; }); }
export async function downloadStaffResume(principal: StaffPrincipal, applicationId: string) { const application = await getStaffApplication(principal, applicationId); if (!application.resume || !principal.companyId || loadConfig().CHIBBO_STORAGE_MODE !== "s3") throw Object.assign(new Error("not found"), { status: 404 }); const config = productionStorage(); const object = await getAcceptedResume(config, { key: application.resume.object_key, versionId: application.resume.object_version_id }); await withTenantTransaction(database(), { ...principal, companyId: principal.companyId }, (client) => client.query("INSERT INTO chibbo.audit_events(company_id,correlation_id,event_scope,event_source,action,target_type,target_id) VALUES($1,$2,$3,$4,$5,$6,$7)", [principal.companyId, randomUUID(), "recruitment-service", "application-audit", "resume.downloaded", "application", applicationId])); return { body: object.Body, mediaType: application.resume.media_type }; }
export async function listAdminCompanies(principal: StaffPrincipal) { if (principal.role !== "platform-admin") throw Object.assign(new Error("not found"), { status: 404 }); return withActorTransaction(database(), principal, async (client) => (await client.query("SELECT * FROM chibbo.list_admin_companies()")).rows); }
export async function listAdminMemberships(principal: StaffPrincipal, companyId: string) { if (principal.role !== "platform-admin") throw Object.assign(new Error("not found"), { status: 404 }); return withActorTransaction(database(), principal, async (client) => (await client.query("SELECT * FROM chibbo.list_admin_memberships($1)", [companyId])).rows); }
export async function manageMembership(principal: StaffPrincipal, input: { companyId: string; tenantId: string; objectId: string; role: "company-manager" | "platform-admin"; active: boolean }) { if (principal.role !== "platform-admin") throw Object.assign(new Error("not found"), { status: 404 }); return withActorTransaction(database(), principal, async (client) => (await client.query("SELECT * FROM chibbo.upsert_admin_membership($1,$2,$3,$4,$5)", [input.companyId, input.tenantId, input.objectId, input.role, input.active])).rows[0]); }
export async function updateApplicationStatus(principal: StaffPrincipal, applicationId: string, status: "reviewing" | "accepted" | "rejected", rowVersion: number) { if (!principal.companyId && principal.role !== "platform-admin") throw Object.assign(new Error("not found"), { status: 404 }); const companyId = principal.companyId; if (!companyId) throw Object.assign(new Error("not found"), { status: 404 }); return withTenantTransaction(database(), { ...principal, companyId }, async (client) => { const current = await client.query("SELECT id,status,row_version FROM chibbo.applications WHERE id=$1", [applicationId]); if (current.rowCount !== 1) throw Object.assign(new Error("not found"), { status: 404 }); const row = current.rows[0]; assertTransition(row.status, status); const changed = await client.query("UPDATE chibbo.applications SET status=$1,row_version=row_version+1 WHERE id=$2 AND row_version=$3", [status, applicationId, rowVersion]); if (changed.rowCount !== 1) throw Object.assign(new Error("stale"), { status: 409 }); await client.query("INSERT INTO chibbo.application_status_events(company_id,application_id,actor_tenant_id,actor_object_id,from_status,to_status,expected_row_version) VALUES($1,$2,$3,$4,$5,$6,$7)", [companyId, applicationId, principal.tenantId, principal.objectId, row.status, status, rowVersion]); return { rowVersion: rowVersion + 1 }; }); }
export async function requestDeletion(receipt: string, secret: string): Promise<void> { const config = loadConfig(); const result = await database().query("SELECT chibbo.consume_deletion_request($1,$2) AS consumed", [receipt, hashDeletionSecret(secret, config.CHIBBO_DELETION_PEPPER)]); if (!result.rows[0]?.consumed) throw new Error("deletion request unavailable"); }
